### ISSUE TITLE
Better support for cloud.gov Service Accounts

### ISSUE THREAD

**Issue by rogeruiz** [18F/cloud-foundry-cli#7]
Because of [cloud.gov Service Accounts](https://cloud.gov/docs/services/cloud-gov-service-account/) being scoped to an org and space, the `cf_deploy.sh` shouldn't require an org or space in order to _better_ enforce deployments using these cloud.gov Service Accounts.

Documentation in the Read Me should also talk about how to set multiple credentials in CircleCI for different deploying to separate spaces since cloud.gov Service Accounts can no longer be shared across spaces.

**Comment by adborden** [comment]
>Because of cloud.gov Service Accounts being scoped to an org and space, the cf_deploy.sh shouldn't require an org or space in order to better enforce deployments using these cloud.gov Service Accounts.

I'm not sure what you mean by this... don't we have to tell `cf` an org/space at some point?

Do you have an example of how you worked around managing the multiple deployer accounts? I was thinking (and I could add this to the docs) you would add multiple env variables in the Circle UI, `DEPLOYER_STAGE_USER`, `DEPLOYER_STAGE_PASS`, `DEPLOYER_DEV_USER`, `DEPLOYER_DEV_PASS`, etc. Then in the configuration or command, you would map them to the variables as expected.
```
jobs:
  build:
    docker:
      - image: 18fgsa/cloud-foundry-cli
        environment:
          CF_API: https://api.fr.cloud.gov
          CF_DEPLOY_USER: $DEPLOY_STAGE_USER
          CF_DEPLOY_PASS: $DEPLOY_STAGE_PASS
    steps:
      - checkout
      - run:
          name: Your build step
          command: ./build.sh
      - deploy:
          name: cf push
          command: cf_deploy.sh app-name org-name space-name
```
or
```
      - deploy:
          name: cf push
          command: cf_deploy.sh app-name org-name space-name
          environment:
            CF_DEPLOY_USER: $DEPLOY_STAGE_USER
            CF_DEPLOY_PASS: $DEPLOY_STAGE_PASS
```
